POST {{host}}/api/v1/vndb?login={{login}}&password={{password}}

get quote basic (id>=1) {"results":1}

###
POST {{host}}/api/v1/vndb

get vn basic,anime,details (id>=1) {"results":20}

###
POST {{host}}/api/v1/vndb

get quote basic (id>=1) {"results":1}

####
POST {{host}}/api/v1/vndb?login={{login}}&password=wrong

get quote basic (id>=1) {"results":1}

###
POST {{host}}/api/v1/vndb?login={{login}}&password={{password}}

get quote basic (id>=1) {"results":20}

###
POST {{host}}/api/v1/vndb?login={{login}}&password={{password}}

get vn basic (firstchar="ze")

###
POST {{host}}/api/v1/vndb?login={{login}}&password={{password}}

dbstats

###
